# Generated by Django 6.0.4 on 2026-05-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_company_email_user_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_gmail_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_sending_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_send_method',
            field=models.CharField(default='fallback', max_length=20),
        ),
    ]
