# Generated by Django 6.0.4 on 2026-05-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_domain_verified_invitetoken_delete_userinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitetoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
