# Generated by Django 6.0.4 on 2026-05-01 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_inspection_payment_collected_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='is_new_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['created_by'], name='inspections_created_682d2e_idx'),
        ),
    ]
