# Generated by Django 6.0.4 on 2026-05-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_business_created_by_business_is_new_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
